export const SELECT_FAVORITES = 'SELECT_FAVORITES';
export const SELECT_SEARCH = 'SELECT_SEARCH';
export const LOOKUP_GEM = 'LOOKUP_GEM';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const LOAD_FAVORITES = 'LOAD_FAVORITES';
export const DISPLAY_FAVORITES = 'DISPLAY_FAVORITES';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';