export const FETCH_DRUGS = 'FETCH_DRUGS';
export const SEARCH_ALT_DRUGS = 'SEARCH_ALT_DRUGS';
export const REMOVE_CURRENT_CONCEPT = 'REMOVE_CURRENT_CONCEPT';
export const REMOVE_ALTERNATIVES = 'REMOVE_ALTERNATIVES';